import course

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='repl.it',
                  resource_url='https://repl.it/'),
    course.Course(period=2,
                  name='Art history',
                  teacher_name='Mr. Long',
                  resource_name='ArtHistory.net',
                  resource_url='http://www.arthistory.net/'),
    course.Course(period=3,
                  name='English',
                  teacher_name='Mr. Moul',
                  resource_name='Spark Notes',
                  resource_url='http://www.sparknotes.com/'),
    course.Course(period=4,
                  name='Physics',
                  teacher_name='Ms. Davis',
                  resource_name='Interactive simulations',
                  resource_url='https://phet.colorado.edu/en/simulations/category/physics'),
    course.Course(period=5,
                  name='Geometry',
                  teacher_name='Ms. Friedeberg',
                  resource_name='Khan Academy',
                  resource_url='https://www.khanacademy.org/math/geometry'),
    course.Course(period=6,
                  name='Biology',
                  teacher_name='Mr. Poulsen',
                  resource_name='Wikipedia',
                  resource_url='https://en.wikipedia.org/wiki/Biology'),
]
